stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw
    outs:
      - data/processed

  train:
    cmd: python train.py
    deps:
      - train.py
      - data/processed
    params:
      - learning_rate
      - epochs
      - batch_size
    outs:
      - models

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models
      - data/processed
    outs:
      - metrics.json
